### ISSUE TITLE
Give example of how to use configuration

### ISSUE THREAD

**Issue by Jameskmonger** [TiagoMestre/inversify-tracer#1]
The readme explains what configuration options can be used, but doesn't say how to actually use this configuration

* in `tracer.apply(kernel, configuration)`?
* in `new InversifyTracer(configuration);`

Some other method?

**Comment by TiagoMestre** [comment]
The configuration is passed in the constructor, example:
```ts
const tracer = new InversifyTracer({
    filters: ["*:*", "!Ninja:*"],
    inspectReturnedPromise: false
});

tracer.apply(kernel);
``` 

I'll update the readme to include this example.

Thanks for the notice.
